//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hiscore.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Icons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Icons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hiscore.Assets.Icons", typeof(Icons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolAgility {
            get {
                object obj = ResourceManager.GetObject("OldSchoolAgility", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolAttack {
            get {
                object obj = ResourceManager.GetObject("OldSchoolAttack", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolConstruction {
            get {
                object obj = ResourceManager.GetObject("OldSchoolConstruction", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolCooking {
            get {
                object obj = ResourceManager.GetObject("OldSchoolCooking", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolCrafting {
            get {
                object obj = ResourceManager.GetObject("OldSchoolCrafting", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolDefense {
            get {
                object obj = ResourceManager.GetObject("OldSchoolDefense", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolFarming {
            get {
                object obj = ResourceManager.GetObject("OldSchoolFarming", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolFiremaking {
            get {
                object obj = ResourceManager.GetObject("OldSchoolFiremaking", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolFishing {
            get {
                object obj = ResourceManager.GetObject("OldSchoolFishing", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolFletching {
            get {
                object obj = ResourceManager.GetObject("OldSchoolFletching", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolHerblore {
            get {
                object obj = ResourceManager.GetObject("OldSchoolHerblore", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolHitpoints {
            get {
                object obj = ResourceManager.GetObject("OldSchoolHitpoints", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolHunter {
            get {
                object obj = ResourceManager.GetObject("OldSchoolHunter", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolMagic {
            get {
                object obj = ResourceManager.GetObject("OldSchoolMagic", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolMining {
            get {
                object obj = ResourceManager.GetObject("OldSchoolMining", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolPrayer {
            get {
                object obj = ResourceManager.GetObject("OldSchoolPrayer", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolRange {
            get {
                object obj = ResourceManager.GetObject("OldSchoolRange", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolRuneCrafting {
            get {
                object obj = ResourceManager.GetObject("OldSchoolRuneCrafting", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolSlayer {
            get {
                object obj = ResourceManager.GetObject("OldSchoolSlayer", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolSmithing {
            get {
                object obj = ResourceManager.GetObject("OldSchoolSmithing", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolStrength {
            get {
                object obj = ResourceManager.GetObject("OldSchoolStrength", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolTheiving {
            get {
                object obj = ResourceManager.GetObject("OldSchoolTheiving", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object OldSchoolWoodcutting {
            get {
                object obj = ResourceManager.GetObject("OldSchoolWoodcutting", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object Overall {
            get {
                object obj = ResourceManager.GetObject("Overall", resourceCulture);
                return ((object)(obj));
            }
        }
    }
}
