on:
  push:
    branches:
      - main

name: build
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Install dotnetcore
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: src/Hiscore/Assets/bin/Release/**/*
